### ISSUE TITLE
How to it debugger/ break points? 

### ISSUE THREAD

**Issue by hdecagny** [edge33/AdventOfCode-2021#1]
Dear Francesco, 

I am rather new to typescript (I come from a c# background), so my apologies if my question is trivial. 

This year, I would like to try to do the advent of code using typescript and I forked your boiler plate repo , that I found quite handy. 
However, I am unable to hit any breakpoint or debugger, using either breakpoints or the debugger inline command. I tried on Rider and on VS code, also using the command `npm run dev 1 --inspect`  (no effect so far). I also tried to tweak a bit the Package.json file and/or the Nodemon.json file, but to be honest, I do not have any idea what I am doing. 

If you have any suggestion to how could i hit breakpoints (this would be handy when it comes to solve more complex puzzles), I would be very grateful. 

Thank you very much for your time, 

kind regards

Henri de Cagny

**Comment by hdecagny** [comment]
Hello, 

I just wanted to say that I managed to deal with my problem. Through rider I found how to start a script which will trigger local breakpoints. 

Kind regards,

**Comment by edge33** [comment]
Hello Henri, I am glad you are appreciating my repo :)
OFC no question is trivial :) so, the thing is, debugging in ts, is different with every IDE or editor you might be using. I mostly use vscode so this is my reference guide: https://code.visualstudio.com/docs/typescript/typescript-debugging
